---
platform: linux
image_resource:
  type: docker-image
  source:
    username: ((dockerid))
    password: ((dockerpwd))
    repository: pivotalservices/pipeline-utilities
outputs:
- name: secrets
run:
  path: pipeline-utilities
  args: [ "env-to-yaml", "--environment-prefix", "PRODUCT", "--output-file", "secrets/product.yml" ]
