---
platform: linux
image_resource:
  type: docker-image
  source:
    username: ((dockerid))
    password: ((dockerpwd))
    repository: pivotalservices/pipeline-utilities
outputs:
- name: config
run:
  path: pipeline-utilities
  args: [ "auth-file", "--output-file", "config/auth.yml" ]
